[build-system]
requires = ["setuptools>=42","wheel","setuptools_scm[toml]>=3.4"]
build_backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "lib/pepugame/version.py"
fallback_version = "0.0.1"